name: Linode Engineering
description: Blog posts from Linode engineerings about engineering at Linode
gems: [jekyll-paginate]
sass:
    style: compressed
    sass_dir: styles/
paginate: 5
paginate_path: "/archive/page:num/"
future: true
