gems: [jekyll-paginate]
sass:
    style: compressed
    load_paths:
        - css/
        - ../styles/ # This is for convenience during dev
        - styles/
paginate: 5
paginate_path: "/archive/page:num/"
